spring:
  application:
    name: unibook
  profiles:
    active: local  # Default to local profile
  datasource:
    url: jdbc:mysql://localhost:3306/unibook_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${DB_PASSWORD:}  # Empty default, actual password in application-local.yml
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Update schema without dropping data
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false  # Development mode
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  cache:
    type: simple  # 개발 환경에서는 simple, 운영에서는 redis 등 사용
    cache-names:
      - schools
      - schoolSearch
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB  # 여러 파일 업로드 시 전체 요청 크기
      file-size-threshold: 2KB  # 메모리에 저장할 임계값

server:
  port: 8080

logging:
  level:
    com.unibook: INFO  # 기본값은 INFO
    org.springframework.web: INFO

# Application specific settings
app:
  home:
    popular-books-limit: 8
    recent-posts-limit: 5
  pagination:
    default-page-size: 20
    max-page-size: 100
  file:
    upload-dir: uploads/
    max-size: 10485760  # 10MB in bytes
    allowed-extensions: jpg,jpeg,png,gif,webp
    post-images:
      path: uploads/posts/
      max-count: 5  # 게시글당 최대 이미지 수